# Raspbian Jessie installation
FROM mglaeske/raspi-nginx

MAINTAINER Frickler24 <frickler24@frickler24.de>
RUN apt-get update 
RUN apt-get -y upgrade 

# Add neccessary files
ADD _etc_nginx_sites-available_default /etc/nginx/sites-available/default
ADD _var_www_html_test.php /var/www/html/test.php
ADD mandel.php /var/www/html/mandel.php
ADD brot.php /var/www/html/brot.php

