lxterm -e ssh pi@andreas &
lxterm -e ssh pi@lutz &
lxterm -e ssh pi@axel &
lxterm -e ssh pi@peter &
lxterm -e ssh pi@heike &
lxterm -e ssh pi@mario &
lxterm -e ssh pi@friedi &
lxterm -e ssh pi@thomas &
lxterm -e ssh pi@thommy &
lxterm -e ssh pi@bettina &
